# This is the template for a single Ubuntu
# build job. This template will publish the
# build artifact with name ${{ parameters.artifactName }}
parameters:
- name: jobName
  type: string
- name: buildType
  type: string
  default: Debug
- name: cmakePreset
  type: string
- name: cmakeExtraArgs
  type: string
  default:
- name: containerName
  type: string
- name: artifactName
  type: string
- name: compiler
  type: string
  default: gcc
- name: compilerStd
  type: string
  default: 17
- name: compilerLibCxx
  type: string
  default: libstdc++11
- name: compilerVersion
  type: string
  default: 11

jobs:
- job: ${{ parameters.jobName }}
  displayName: Ubuntu ${{ parameters.cmakePreset }}
  continueOnError: false
  container: ${{ parameters.containerName }}
  steps:
    - ${{ if eq(parameters.buildType, 'Debug') }}:
      - bash: |
          COMPILER=${{ parameters.compiler }} \
          COMPILER_STD=${{ parameters.compilerStd }} \
          COMPILER_LIBCXX=${{ parameters.compilerLibCxx }} \
          COMPILER_VERSION=${{ parameters.compilerVersion }} \
          BUILD_TYPE=${{ parameters.buildType }} \
          scripts/helpers/conan-install.sh
        displayName: Installing Conan Dependencies

    - bash: |
        set -euo pipefail
        scripts/build_x86-64.sh ${{ parameters.cmakePreset }} ${{ parameters.cmakeExtraArgs }}
      displayName: Compile Code & Tests

    - bash: |
        set -euo pipefail
        scripts/cmake-install.sh ${{ parameters.cmakePreset }}
      displayName: Install Library

    - task: PublishBuildArtifacts@1
      displayName: Publishing Build Files
      inputs:
        PathToPublish: $(Build.SourcesDirectory)/build
        StoreAsTar: true
        ArtifactName: ${{ parameters.artifactName }}