# This is the template for a single Ubuntu
# build job. This template will publish the
# build artifact with name ${{ parameters.artifactName }}
parameters:
- name: jobName
  type: string
- name: buildType
  type: string
  default: Debug
- name: cmakePreset
  type: string
- name: cmakeExtraArgs
  type: string
  default:
- name: containerName
  type: string
- name: artifactName
  type: string


jobs:
- job: ${{ parameters.jobName }}
  displayName: Ubuntu ${{ parameters.buildType }} ${{ parameters.jobName }}
  continueOnError: false
  container: ${{ parameters.containerName }}
  steps:
    - ${{ if eq(parameters.buildType, 'Debug') }}:
      - bash: scripts/helpers/conan-install.sh ${{ parameters.buildType }}
        displayName: Installing Conan Dependencies

    - bash: |
        set -euo pipefail
        scripts/build_x86-64.sh ${{ parameters.cmakePreset }} ${{ parameters.cmakeExtraArgs }}
      displayName: Compile Code & Tests

    - bash: |
        set -euo pipefail
        scripts/cmake-install.sh ${{ parameters.cmakePreset }}
      displayName: Install Library

    - task: PublishBuildArtifacts@1
      displayName: Publishing Build Files
      inputs:
        PathToPublish: $(Build.SourcesDirectory)/build
        StoreAsTar: true
        ArtifactName: ${{ parameters.artifactName }}