# This is the template for a single Windows
# build job. This template will publish the
# build artifact with name ${{ parameters.artifactName }}
parameters:
- name: jobName
  type: string
- name: buildType
  type: string
  default: Debug
- name: cmakePreset
  type: string
- name: cmakeExtraArgs # TODO Do we need to support this?
  type: string
  default:
- name: artifactName
  type: string

jobs:
- job: ${{ parameters.jobName }}
  displayName: Windows ${{ parameters.buildType }} ${{ parameters.jobName }}
  continueOnError: false
  pool:
    vmImage: windows-2022
  steps:

    - ${{ if eq(parameters.buildType, 'Debug') }}:
      - pwsh: .\scripts\helpers\install-dependencies.ps1 -BuildType ${{ parameters.buildType }}
        displayName: Installing Conan Dependencies

    - pwsh: |
        .\scripts\build_win_x64.ps1 -Preset ${{ parameters.cmakePreset }}
      displayName: Compile Code & Tests
      failOnStderr: true
    
    - pwsh: |
        .\scripts\cmake-install.ps1 -Preset ${{ parameters.cmakePreset }}
      displayName: Install Library

    - task: PublishBuildArtifacts@1
      displayName: Publish Build Files
      inputs:
        PathToPublish: "$(Build.SourcesDirectory)/build"
        ArtifactName: ${{ parameters.artifactName }}